server.port = 8888
spring.application.name=config-server

#spring.cloud.config.server.native.search-locations=file:/home/azureuser/config-repo
spring.cloud.config.server.native.search-locations=file:///C:/Users/treso/deploy/config-repo
spring.profiles.active=native
